#_render.yaml
"""
Why “worker”? not serving a web app—
your bot just needs to stay alive and optionally answer health checks. 
Render won’t try to probe ports, and you won’t consume free-tier web minutes.
"""
services:
  - type: worker
    name: discord-bot
    env:
      - key: DIS_TOKEN
      - key: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_ROLE_KEY
      - key: SUPABASE_JWT_SECRET
      - key: LOGFLARE_API_KEY
      - key: LOGFLARE_SOURCE_ID
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py


    # Enable and persist pip cache across builds:
    # cacheDirectories:
    #   - $HOME/.cache/pip

    # buildCommand: |
    #   export PIP_CACHE_DIR=$HOME/.cache/pip
    #   mkdir -p $PIP_CACHE_DIR
    #   pip install -r requirements.txt
