#_render.yaml
services:
  - type: web
    name: discord-bot
    # Python needs to know where to find your modules:
    envVars:
      - key: PYTHONPATH
        value: .
    env:
      - key: DIS_TOKEN
      - key: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_ROLE_KEY
      - key: SUPABASE_JWT_SECRET
      - key: LOGFLARE_API_KEY
      - key: LOGFLARE_SOURCE_ID

    # Enable and persist pip cache across builds:
    cacheDirectories:
      - $HOME/.cache/pip

    buildCommand: |
      export PIP_CACHE_DIR=$HOME/.cache/pip
      mkdir -p $PIP_CACHE_DIR
      pip install -r requirements.txt

    startCommand: python bot.py
