services:
  - type: worker
    name: discord-bot
    env:
      - key: DIS_TOKEN
      - key: SUPABASE_URL
      - key: SUPABASE_ANON_KEY
      - key: SUPABASE_SERVICE_ROLE_KEY
      - key: SUPABASE_JWT_SECRET
    buildCommand: |
      export PIP_CACHE_DIR=$HOME/.cache/pip
      mkdir -p $PIP_CACHE_DIR
      pip install -r requirements.txt
    startCommand: python main.py
